### ISSUE TITLE
Possibility of backport to 1.19.2

### ISSUE THREAD

**Issue by rafaelhr** [DavidQF555/Multiverse#3]
I'd like to know if it was possible to backport this mod to version 1.19.2, since there are more mods in the 1.19 ecosystem that haven't been updated to 1.19.4 than mods that have been updated to that version. I don't know how easy or hard this would be, but if it's not too inconvenient, it would be nice.

Thanks anyway, your mod seems amazing!

**Comment by vgrynch** [comment]
Plus here. 1.19.2 mods are the most downloadable, so the majority modpacks are using 1.19.2 version. Please, add 1.19.2.

**Comment by DavidQF555** [comment]
I will try this when I have time. It seems a bit strange because I don't really see a point staying on 1.19.2 over 1.19.4, but I guess some mods haven't been updated. I doubt I will actively maintain a 1.19.2 version, but I can definitely release a working version.

**Comment by DavidQF555** [comment]
I've successfully ported from 1.19.4 to 1.19.2.
